# Generated by Django 4.2.4 on 2023-08-12 14:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('select_application_type', models.CharField(choices=[('application type 1', 'application type 1'), ('application type 2', 'application type 2'), ('application type 3', 'application type 3')], max_length=50)),
                ('service_details', models.CharField(max_length=200)),
                ('attach_file', models.FileField(upload_to='application_files/')),
                ('submission_datetime', models.DateTimeField()),
                ('status', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
